#!/bin/bash
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

function help () {
        echo " "
        echo ""
        echo "example usage:"
        echo "check_owncloud_quota!/tmp/quota"
}

ARGV=$@
ARGC=$#
if [[ $1 == "--help" ]];then
        help
elif [[ $1 == "-h" ]];then
        help
else
                gather=`cat $1`
                used=`echo $gather| cut -d "-" -f2`
                max=`echo $gather|cut -d "-" -f3`
                WARN=`echo $max*0.7|bc|cut -d "." -f1`

                        if  [ $used -gt $WARN ] ; then
                                echo "used: ${used} B of allowed: $max B|B=${used};;$max B;; & 'total B'=$max;;;;"
                                exit $STATE_WARNING

                        elif [ $used -lt $WARN ] ; then
                                echo "used: ${used} B of allowed: $max B|B=${used};;$max B;; & 'total B'=$max;;;;"
                                exit $STATE_OK
                        else
                                echo "UNKNOWN" $check
                                exit $STATE_UNKNOWN
                        fi
fi
