#!/bin/bash
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

function help () {
        echo " "
        echo ""
        echo "example usage:"
        echo "check_owncloud_quota username"
}

if [ ! -n "$1" ];then
        help
else
                gather="`cat /tmp/quota|grep -w -i $1 `"
                used=`echo $gather|tr -d . | cut -d "-" -f2`
                max=`echo $gather|tr -d . |cut -d "-" -f3`
                WARN=`echo $max*0.7|bc|cut -d "." -f1`

                        if  [ $used -gt $WARN ] ; then
                                echo "MB used: ${used} allowed: $max MB|MB=${used};;$max MB;; & 'total MB'=$max;;;;"
                                exit $STATE_WARNING

                        elif [ $used -lt $WARN ] ; then
                                echo "MB used: ${used} allowed: $max MB|MB=${used};;$max MB;; & 'total MB'=$max;;;;"
                                exit $STATE_OK
                        else
                                echo "UNKNOWN" $check
                                exit $STATE_UNKNOWN
                        fi
fi
